# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Branch < Formula
  desc ""
  homepage "https://github.com/abroudoux/branch"
  version "0.1.2"

  on_macos do
    url "https://github.com/abroudoux/branch/releases/download/v0.1.2/branch_0.1.2_darwin_all.tar.gz"
    sha256 "8971bf661f826bcfeb112532c42b709c9ef8606792cbe6f0a5e66411b535e95a"

    def install
      bin.install "branch"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.1.2/branch_0.1.2_linux_amd64.tar.gz"
        sha256 "10cd26f3b1ff73ba3f1195bd42176fff2a4a3d65825b9943b3ca7f82d4d327f6"

        def install
          bin.install "branch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.1.2/branch_0.1.2_linux_arm64.tar.gz"
        sha256 "bac8802019af32ebd90162665b3d37e325411d769cc46deaa3d1b8309cae17e4"

        def install
          bin.install "branch"
        end
      end
    end
  end
end
