# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Branch < Formula
  desc ""
  homepage "https://github.com/abroudoux/branch"
  version "0.2.2"

  on_macos do
    url "https://github.com/abroudoux/branch/releases/download/v0.2.2/branch_0.2.2_darwin_all.tar.gz"
    sha256 "d4ff83b8c87c5abbc56b0c48cf4a669e2d5396076ff428c9c1ddd89a27458089"

    def install
      bin.install "branch"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.2.2/branch_0.2.2_linux_amd64.tar.gz"
        sha256 "b9156eb75ab61722806c0dbf80247e75c507a177ae776daa20896140c2420d69"

        def install
          bin.install "branch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.2.2/branch_0.2.2_linux_arm64.tar.gz"
        sha256 "7ac962ebc6b2fccb0956d46c4e5b6c51a786fe10f40b19e08768b619d35e41fe"

        def install
          bin.install "branch"
        end
      end
    end
  end
end
