# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Branch < Formula
  desc ""
  homepage "https://github.com/abroudoux/branch"
  version "0.2.1"

  on_macos do
    url "https://github.com/abroudoux/branch/releases/download/v0.2.1/branch_0.2.1_darwin_all.tar.gz"
    sha256 "089035050c4e23dad7986119def0035ffa7ad7698bc222e3572fda0ffcd5e01f"

    def install
      bin.install "branch"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.2.1/branch_0.2.1_linux_amd64.tar.gz"
        sha256 "79099088ae4296ee38d98153ae9543d017f4ba9b493eecec908406e6ae1ece89"

        def install
          bin.install "branch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/branch/releases/download/v0.2.1/branch_0.2.1_linux_arm64.tar.gz"
        sha256 "37750edffc41f14a9dbff270d364d490a01d983c4c841a38af9761d7cb3e65c9"

        def install
          bin.install "branch"
        end
      end
    end
  end
end
