# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dk < Formula
  desc ""
  homepage "https://github.com/abroudoux/dk"
  version "0.2.1"

  on_macos do
    url "https://github.com/abroudoux/dk/releases/download/v0.2.1/dk_0.2.1_darwin_all.tar.gz"
    sha256 "212cde3591eacf92c705672dc52438c8ed2e691a42bfeac2260a0a4a3853ed52"

    def install
      bin.install "dk"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.2.1/dk_0.2.1_linux_amd64.tar.gz"
        sha256 "fdc3cb7953684770024e3b73909f8a4d5c65383b2945644c6a408af535d0f301"

        def install
          bin.install "dk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.2.1/dk_0.2.1_linux_arm64.tar.gz"
        sha256 "511d314968c8737fd9165f65f6b5d27e79c160b73d58330e879a2251a38ad7ca"

        def install
          bin.install "dk"
        end
      end
    end
  end
end
