# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dk < Formula
  desc ""
  homepage "https://github.com/abroudoux/dk"
  version "0.2.0"

  on_macos do
    url "https://github.com/abroudoux/dk/releases/download/v0.2.0/dk_0.2.0_darwin_all.tar.gz"
    sha256 "c0d1bf854663de11a8d82a7477866cebff981fad734947324ab4efacc54195b2"

    def install
      bin.install "dk"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.2.0/dk_0.2.0_linux_amd64.tar.gz"
        sha256 "881788cf11b5355724725a16863b55bbd50f5aa7ea304f50a78b6c3321882ac4"

        def install
          bin.install "dk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.2.0/dk_0.2.0_linux_arm64.tar.gz"
        sha256 "56a06b20b08fc8a41c56be19c557c367edbad7fa0a99dd1bcc40bb613745e5a0"

        def install
          bin.install "dk"
        end
      end
    end
  end
end
