# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dk < Formula
  desc ""
  homepage "https://github.com/abroudoux/dk"
  version "0.3.1"

  on_macos do
    url "https://github.com/abroudoux/dk/releases/download/v0.3.1/dk_0.3.1_darwin_all.tar.gz"
    sha256 "be42a7f0ca39a6cc0f1dd3754927ab1c2b7807b5ccc6610dde3894bca23c9a74"

    def install
      bin.install "dk"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.3.1/dk_0.3.1_linux_amd64.tar.gz"
        sha256 "82719d58a023b5bc23f55e08863b8ddfa0515d68ffb91dc8f1a102bbd0bffb94"

        def install
          bin.install "dk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/dk/releases/download/v0.3.1/dk_0.3.1_linux_arm64.tar.gz"
        sha256 "354d53cc70fb446f0411be6b425df3eea16e190935ae48a409fe627e02ebcdcf"

        def install
          bin.install "dk"
        end
      end
    end
  end
end
