# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trad < Formula
  desc ""
  homepage "https://github.com/abroudoux/trad"
  version "0.0.1"

  on_macos do
    url "https://github.com/abroudoux/trad/releases/download/v0.0.1/trad_0.0.1_darwin_all.tar.gz"
    sha256 "a174f97ea7e23940e9fbc52eb479f4ed6cdd961d67cac7a16fa4f093d6872d41"

    def install
      bin.install "trad"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/trad/releases/download/v0.0.1/trad_0.0.1_linux_amd64.tar.gz"
        sha256 "7f4512e575e68535c993c0235022b8d7465808dd627ee6aec6fec68097726430"

        def install
          bin.install "trad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abroudoux/trad/releases/download/v0.0.1/trad_0.0.1_linux_arm64.tar.gz"
        sha256 "fd0aecfda2f33c67d3ce2592090d3d2899acb44bae0b79e047b0b8bdf306b67c"

        def install
          bin.install "trad"
        end
      end
    end
  end
end
